"""descriptive message

Revision ID: 5c787d49cc37
Revises: 9df0680be93d
Create Date: 2025-09-28 22:22:07.638854

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5c787d49cc37'
down_revision = '9df0680be93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
