"""descriptive message

Revision ID: 7f339277add8
Revises: e7f787ad56e1
Create Date: 2025-09-28 11:44:59.470769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f339277add8'
down_revision = 'e7f787ad56e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_order_deleted_at'), 'order', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_deleted_at'), table_name='order')
    op.drop_column('order', 'deleted_by')
    op.drop_column('order', 'deleted_at')
    # ### end Alembic commands ###
