"""descriptive message

Revision ID: 9df0680be93d
Revises: db024eba5052
Create Date: 2025-09-28 21:54:41.905481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9df0680be93d'
down_revision = 'db024eba5052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'order', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'owner_id')
    # ### end Alembic commands ###
