"""init schema

Revision ID: e7f787ad56e1
Revises: 
Create Date: 2025-09-25 22:47:58.871644

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e7f787ad56e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('alpaca_buy_order_id', sa.Uuid(), nullable=True),
    sa.Column('alpaca_sell_order_id', sa.Uuid(), nullable=True),
    sa.Column('alpaca_client_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('force_sell_at', sa.DateTime(), nullable=True),
    sa.Column('buy_filled_avg_price', sa.Float(), nullable=True),
    sa.Column('buy_filled_qty', sa.Float(), nullable=True),
    sa.Column('sell_filled_avg_price', sa.Float(), nullable=True),
    sa.Column('sell_filled_qty', sa.Float(), nullable=True),
    sa.Column('target_profit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'BUY_PENDING_NEW', 'BUY_ACCEPTED', 'BUY_FILLED', 'SELL_PENDING_NEW', 'SELL_ACCEPTED', 'SELL_FILLED', name='virtualorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_alpaca_buy_order_id'), 'order', ['alpaca_buy_order_id'], unique=True)
    op.create_index(op.f('ix_order_alpaca_sell_order_id'), 'order', ['alpaca_sell_order_id'], unique=True)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_order_alpaca_sell_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_alpaca_buy_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
